services:
  mariadb:
    image: mariadb:11.2
    container_name: personal-finance-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword123}
      MARIADB_DATABASE: ${DB_NAME:-personal_finance}
      MARIADB_USER: ${DB_USER:-finance_user}
      MARIADB_PASSWORD: ${DB_PASSWORD:-finance_user_password_2024}
      MARIADB_CHARACTER_SET_SERVER: utf8mb4
      MARIADB_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./sql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    ports:
      - "${DB_PORT:-3306}:3306"
    networks:
      - finance-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  redis:
    image: redis:7.2-alpine
    container_name: personal-finance-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis_password_2024} --appendonly yes --appendfsync everysec
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis_password_2024}
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - finance-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

  app:
    image: node:20-alpine
    container_name: MyMoney
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=${DB_NAME:-personal_finance}
      - DB_USER=${DB_USER:-finance_user}
      - DB_PASSWORD=${DB_PASSWORD:-finance_user_password_2024}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-rootpassword123}
      - DB_SSL=false
      - DB_CHARSET=utf8mb4
      - DB_COLLATION=utf8mb4_unicode_ci
      - DB_TIMEZONE=+00:00
      - DB_CONNECTION_LIMIT=10
      - DB_ACQUIRE_TIMEOUT=60000
      - DB_TIMEOUT=60000
      - APP_PORT=${APP_PORT:-3001}
      - JWT_SECRET=${JWT_SECRET:-your_super_secure_jwt_secret_key_here_minimum_32_characters}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-your_super_secure_refresh_secret_key_here_minimum_32_characters}
      - JWT_EXPIRES_IN=15m
      - JWT_REFRESH_EXPIRES_IN=7d
      - BCRYPT_ROUNDS=12
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - AUTH_RATE_LIMIT_MAX=5
      - STRICT_RATE_LIMIT_MAX=10
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis_password_2024}
      - REDIS_DB=0
      - REDIS_URL=${REDIS_URL:-redis://:redis_password_2024@redis:6379}
      - CACHE_TTL_DEFAULT=300
      - UPLOAD_DIR=/app/uploads
      - MAX_FILE_SIZE=10485760
      - API_TIMEOUT=30000
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:5173,http://localhost:3001}
      - LOG_LEVEL=info
      - LOG_DIR=/app/logs
      - BACKUP_ENABLED=true
      - BACKUP_INTERVAL=24
      - BACKUP_RETENTION_DAYS=30
      - BACKUP_DIR=/app/backups
      - NODE_OPTIONS=--max-old-space-size=512
    ports:
      - "${APP_PORT:-3001}:3001"
    volumes:
      - .:/app
      - app_uploads:/app/uploads
      - app_logs:/app/logs
      - app_backups:/app/backups
    working_dir: /app
    command: sh -c "npm install --production && npm start"
    networks:
      - finance-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

volumes:
  mariadb_data:
    driver: local
  redis_data:
    driver: local
  app_uploads:
    driver: local
  app_logs:
    driver: local
  app_backups:
    driver: local

networks:
  finance-network:
    driver: bridge