version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.debug
    container_name: MyMoney-Test
    environment:
      - NODE_ENV=development
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=mymoney
      - DB_USER=finance_user
      - DB_PASSWORD=finance_user_password_2024
      - APP_PORT=3001
    ports:
      - "3001:3001"
    # Sem external_links para simplificar o teste
    networks:
      - default

networks:
  default:
    external: true
    name: bridge